version: '3'
services:
  frontoffice:
    image: node:12.19.0-alpine
    working_dir: "/usr/src/app"
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
    command: sh -c "yarn install && yarn dev"
