
name: Push Check Pipeline

on: 
  push:
    paths:
      - 'app/**'
  pull_request:
    paths:
      - 'app/**'
    
jobs:
  pre_job:
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}
          paths: '["app/**"]'

  check-frontoffice:
    name: Build & Lint Frontoffice
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn

      - name: Enforce js code style
        run: yarn lint:js

      - name: Enforce styles code style
        run: yarn lint:style

      - name: Build without failing
        run: yarn build
